create table "public"."addresses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "address" text not null,
    "name" text not null,
    "club_id" bigint
);


create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


create table "public"."club_groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "club_id" bigint not null,
    "address_id" bigint not null,
    "max_occupancy" numeric not null,
    "start_time" time without time zone not null,
    "once_in_number_of_weeks" numeric not null default '1'::numeric,
    "day" text not null,
    "end_time" time without time zone not null
);


create table "public"."clubs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "contact_person" text not null,
    "category_id" bigint
);


create table "public"."group_trainings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "group_id" bigint,
    "club_id" bigint,
    "max_occupancy" numeric not null,
    "start_timestamp" timestamp without time zone not null,
    "end_timestamp" timestamp without time zone not null
);


create table "public"."history_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event" text not null,
    "group_id" bigint not null,
    "training_id" bigint not null
);


create table "public"."join_group_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "group_id" bigint not null,
    "is_accepted" boolean not null default false,
    "is_rejected" boolean not null default false,
    "comments" text
);


create table "public"."join_training_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "training_id" bigint not null,
    "is_accepted" boolean not null default false,
    "is_rejected" boolean not null default false,
    "comments" text
);


create table "public"."notices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "notice" text not null,
    "training_id" bigint,
    "group_id" bigint
);


create table "public"."promo_codes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null,
    "is_used" boolean not null default false,
    "is_used_time" timestamp without time zone
);


create table "public"."trainers_groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "trainer_id" bigint not null,
    "club_group_id" bigint not null
);


create table "public"."trainers_trainings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "trainer_id" bigint not null,
    "training_id" bigint not null
);


create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text not null,
    "email" text not null,
    "phone" text not null,
    "profile_image" text,
    "userId" uuid not null,
    "club_id" bigint,
    "is_trainer" boolean not null default false
);


create table "public"."users_groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "club_group_id" bigint not null
);


create table "public"."users_trainings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "training_id" bigint not null,
    "marked_absent" boolean default false,
    "marked_absent_timestamp" timestamp with time zone,
    "promo_code_id" bigint
);


CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX club_group_pkey ON public.club_groups USING btree (id);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX group_trainings_pkey ON public.group_trainings USING btree (id);

CREATE UNIQUE INDEX history_events_pkey ON public.history_events USING btree (id);

CREATE UNIQUE INDEX join_group_requests_pkey ON public.join_group_requests USING btree (id);

CREATE UNIQUE INDEX join_training_requests_pkey ON public.join_training_requests USING btree (id);

CREATE UNIQUE INDEX notices_pkey ON public.notices USING btree (id);

CREATE UNIQUE INDEX promo_codes_code_key ON public.promo_codes USING btree (code);

CREATE UNIQUE INDEX promo_codes_pkey ON public.promo_codes USING btree (id);

CREATE UNIQUE INDEX trainers_groups_pkey ON public.users_groups USING btree (id);

CREATE UNIQUE INDEX trainers_groups_pkey1 ON public.trainers_groups USING btree (id);

CREATE UNIQUE INDEX trainers_trainings_pkey ON public.users_trainings USING btree (id);

CREATE UNIQUE INDEX trainers_trainings_pkey1 ON public.trainers_trainings USING btree (id);

CREATE UNIQUE INDEX users_id_key ON public.users USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."club_groups" add constraint "club_group_pkey" PRIMARY KEY using index "club_group_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."group_trainings" add constraint "group_trainings_pkey" PRIMARY KEY using index "group_trainings_pkey";

alter table "public"."history_events" add constraint "history_events_pkey" PRIMARY KEY using index "history_events_pkey";

alter table "public"."join_group_requests" add constraint "join_group_requests_pkey" PRIMARY KEY using index "join_group_requests_pkey";

alter table "public"."join_training_requests" add constraint "join_training_requests_pkey" PRIMARY KEY using index "join_training_requests_pkey";

alter table "public"."notices" add constraint "notices_pkey" PRIMARY KEY using index "notices_pkey";

alter table "public"."promo_codes" add constraint "promo_codes_pkey" PRIMARY KEY using index "promo_codes_pkey";

alter table "public"."trainers_groups" add constraint "trainers_groups_pkey1" PRIMARY KEY using index "trainers_groups_pkey1";

alter table "public"."trainers_trainings" add constraint "trainers_trainings_pkey1" PRIMARY KEY using index "trainers_trainings_pkey1";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."users_groups" add constraint "trainers_groups_pkey" PRIMARY KEY using index "trainers_groups_pkey";

alter table "public"."users_trainings" add constraint "trainers_trainings_pkey" PRIMARY KEY using index "trainers_trainings_pkey";

alter table "public"."addresses" add constraint "addresses_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) not valid;

alter table "public"."addresses" validate constraint "addresses_club_id_fkey";

alter table "public"."club_groups" add constraint "club_group_address_id_fkey" FOREIGN KEY (address_id) REFERENCES addresses(id) not valid;

alter table "public"."club_groups" validate constraint "club_group_address_id_fkey";

alter table "public"."club_groups" add constraint "club_group_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) not valid;

alter table "public"."club_groups" validate constraint "club_group_club_id_fkey";

alter table "public"."clubs" add constraint "clubs_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."clubs" validate constraint "clubs_category_id_fkey";

alter table "public"."group_trainings" add constraint "group_trainings_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) not valid;

alter table "public"."group_trainings" validate constraint "group_trainings_club_id_fkey";

alter table "public"."group_trainings" add constraint "group_trainings_group_id_fkey" FOREIGN KEY (group_id) REFERENCES club_groups(id) not valid;

alter table "public"."group_trainings" validate constraint "group_trainings_group_id_fkey";

alter table "public"."history_events" add constraint "history_events_group_id_fkey" FOREIGN KEY (group_id) REFERENCES club_groups(id) not valid;

alter table "public"."history_events" validate constraint "history_events_group_id_fkey";

alter table "public"."history_events" add constraint "history_events_training_id_fkey" FOREIGN KEY (training_id) REFERENCES group_trainings(id) not valid;

alter table "public"."history_events" validate constraint "history_events_training_id_fkey";

alter table "public"."join_group_requests" add constraint "join_group_requests_group_id_fkey" FOREIGN KEY (group_id) REFERENCES club_groups(id) not valid;

alter table "public"."join_group_requests" validate constraint "join_group_requests_group_id_fkey";

alter table "public"."join_group_requests" add constraint "join_group_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."join_group_requests" validate constraint "join_group_requests_user_id_fkey";

alter table "public"."join_training_requests" add constraint "join_training_requests_group_id_fkey" FOREIGN KEY (training_id) REFERENCES club_groups(id) not valid;

alter table "public"."join_training_requests" validate constraint "join_training_requests_group_id_fkey";

alter table "public"."join_training_requests" add constraint "join_training_requests_training_id_fkey" FOREIGN KEY (training_id) REFERENCES group_trainings(id) not valid;

alter table "public"."join_training_requests" validate constraint "join_training_requests_training_id_fkey";

alter table "public"."join_training_requests" add constraint "join_training_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."join_training_requests" validate constraint "join_training_requests_user_id_fkey";

alter table "public"."notices" add constraint "notices_group_id_fkey" FOREIGN KEY (group_id) REFERENCES club_groups(id) not valid;

alter table "public"."notices" validate constraint "notices_group_id_fkey";

alter table "public"."notices" add constraint "notices_training_id_fkey" FOREIGN KEY (training_id) REFERENCES group_trainings(id) not valid;

alter table "public"."notices" validate constraint "notices_training_id_fkey";

alter table "public"."promo_codes" add constraint "promo_codes_code_key" UNIQUE using index "promo_codes_code_key";

alter table "public"."trainers_groups" add constraint "trainers_groups_club_group_id_fkey1" FOREIGN KEY (club_group_id) REFERENCES club_groups(id) not valid;

alter table "public"."trainers_groups" validate constraint "trainers_groups_club_group_id_fkey1";

alter table "public"."trainers_groups" add constraint "trainers_groups_user_id_fkey" FOREIGN KEY (trainer_id) REFERENCES users(id) not valid;

alter table "public"."trainers_groups" validate constraint "trainers_groups_user_id_fkey";

alter table "public"."trainers_trainings" add constraint "trainers_trainings_training_id_fkey1" FOREIGN KEY (training_id) REFERENCES group_trainings(id) not valid;

alter table "public"."trainers_trainings" validate constraint "trainers_trainings_training_id_fkey1";

alter table "public"."trainers_trainings" add constraint "trainers_trainings_user_id_fkey" FOREIGN KEY (trainer_id) REFERENCES users(id) not valid;

alter table "public"."trainers_trainings" validate constraint "trainers_trainings_user_id_fkey";

alter table "public"."users" add constraint "users_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) not valid;

alter table "public"."users" validate constraint "users_club_id_fkey";

alter table "public"."users" add constraint "users_id_key" UNIQUE using index "users_id_key";

alter table "public"."users" add constraint "users_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_userId_fkey";

alter table "public"."users_groups" add constraint "trainers_groups_club_group_id_fkey" FOREIGN KEY (club_group_id) REFERENCES club_groups(id) not valid;

alter table "public"."users_groups" validate constraint "trainers_groups_club_group_id_fkey";

alter table "public"."users_groups" add constraint "trainers_groups_trainer_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."users_groups" validate constraint "trainers_groups_trainer_id_fkey";

alter table "public"."users_trainings" add constraint "trainers_trainings_trainer_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."users_trainings" validate constraint "trainers_trainings_trainer_id_fkey";

alter table "public"."users_trainings" add constraint "trainers_trainings_training_id_fkey" FOREIGN KEY (training_id) REFERENCES group_trainings(id) not valid;

alter table "public"."users_trainings" validate constraint "trainers_trainings_training_id_fkey";

alter table "public"."users_trainings" add constraint "users_trainings_promo_code_id_fkey" FOREIGN KEY (promo_code_id) REFERENCES promo_codes(id) not valid;

alter table "public"."users_trainings" validate constraint "users_trainings_promo_code_id_fkey";

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."club_groups" to "anon";

grant insert on table "public"."club_groups" to "anon";

grant references on table "public"."club_groups" to "anon";

grant select on table "public"."club_groups" to "anon";

grant trigger on table "public"."club_groups" to "anon";

grant truncate on table "public"."club_groups" to "anon";

grant update on table "public"."club_groups" to "anon";

grant delete on table "public"."club_groups" to "authenticated";

grant insert on table "public"."club_groups" to "authenticated";

grant references on table "public"."club_groups" to "authenticated";

grant select on table "public"."club_groups" to "authenticated";

grant trigger on table "public"."club_groups" to "authenticated";

grant truncate on table "public"."club_groups" to "authenticated";

grant update on table "public"."club_groups" to "authenticated";

grant delete on table "public"."club_groups" to "service_role";

grant insert on table "public"."club_groups" to "service_role";

grant references on table "public"."club_groups" to "service_role";

grant select on table "public"."club_groups" to "service_role";

grant trigger on table "public"."club_groups" to "service_role";

grant truncate on table "public"."club_groups" to "service_role";

grant update on table "public"."club_groups" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."group_trainings" to "anon";

grant insert on table "public"."group_trainings" to "anon";

grant references on table "public"."group_trainings" to "anon";

grant select on table "public"."group_trainings" to "anon";

grant trigger on table "public"."group_trainings" to "anon";

grant truncate on table "public"."group_trainings" to "anon";

grant update on table "public"."group_trainings" to "anon";

grant delete on table "public"."group_trainings" to "authenticated";

grant insert on table "public"."group_trainings" to "authenticated";

grant references on table "public"."group_trainings" to "authenticated";

grant select on table "public"."group_trainings" to "authenticated";

grant trigger on table "public"."group_trainings" to "authenticated";

grant truncate on table "public"."group_trainings" to "authenticated";

grant update on table "public"."group_trainings" to "authenticated";

grant delete on table "public"."group_trainings" to "service_role";

grant insert on table "public"."group_trainings" to "service_role";

grant references on table "public"."group_trainings" to "service_role";

grant select on table "public"."group_trainings" to "service_role";

grant trigger on table "public"."group_trainings" to "service_role";

grant truncate on table "public"."group_trainings" to "service_role";

grant update on table "public"."group_trainings" to "service_role";

grant delete on table "public"."history_events" to "anon";

grant insert on table "public"."history_events" to "anon";

grant references on table "public"."history_events" to "anon";

grant select on table "public"."history_events" to "anon";

grant trigger on table "public"."history_events" to "anon";

grant truncate on table "public"."history_events" to "anon";

grant update on table "public"."history_events" to "anon";

grant delete on table "public"."history_events" to "authenticated";

grant insert on table "public"."history_events" to "authenticated";

grant references on table "public"."history_events" to "authenticated";

grant select on table "public"."history_events" to "authenticated";

grant trigger on table "public"."history_events" to "authenticated";

grant truncate on table "public"."history_events" to "authenticated";

grant update on table "public"."history_events" to "authenticated";

grant delete on table "public"."history_events" to "service_role";

grant insert on table "public"."history_events" to "service_role";

grant references on table "public"."history_events" to "service_role";

grant select on table "public"."history_events" to "service_role";

grant trigger on table "public"."history_events" to "service_role";

grant truncate on table "public"."history_events" to "service_role";

grant update on table "public"."history_events" to "service_role";

grant delete on table "public"."join_group_requests" to "anon";

grant insert on table "public"."join_group_requests" to "anon";

grant references on table "public"."join_group_requests" to "anon";

grant select on table "public"."join_group_requests" to "anon";

grant trigger on table "public"."join_group_requests" to "anon";

grant truncate on table "public"."join_group_requests" to "anon";

grant update on table "public"."join_group_requests" to "anon";

grant delete on table "public"."join_group_requests" to "authenticated";

grant insert on table "public"."join_group_requests" to "authenticated";

grant references on table "public"."join_group_requests" to "authenticated";

grant select on table "public"."join_group_requests" to "authenticated";

grant trigger on table "public"."join_group_requests" to "authenticated";

grant truncate on table "public"."join_group_requests" to "authenticated";

grant update on table "public"."join_group_requests" to "authenticated";

grant delete on table "public"."join_group_requests" to "service_role";

grant insert on table "public"."join_group_requests" to "service_role";

grant references on table "public"."join_group_requests" to "service_role";

grant select on table "public"."join_group_requests" to "service_role";

grant trigger on table "public"."join_group_requests" to "service_role";

grant truncate on table "public"."join_group_requests" to "service_role";

grant update on table "public"."join_group_requests" to "service_role";

grant delete on table "public"."join_training_requests" to "anon";

grant insert on table "public"."join_training_requests" to "anon";

grant references on table "public"."join_training_requests" to "anon";

grant select on table "public"."join_training_requests" to "anon";

grant trigger on table "public"."join_training_requests" to "anon";

grant truncate on table "public"."join_training_requests" to "anon";

grant update on table "public"."join_training_requests" to "anon";

grant delete on table "public"."join_training_requests" to "authenticated";

grant insert on table "public"."join_training_requests" to "authenticated";

grant references on table "public"."join_training_requests" to "authenticated";

grant select on table "public"."join_training_requests" to "authenticated";

grant trigger on table "public"."join_training_requests" to "authenticated";

grant truncate on table "public"."join_training_requests" to "authenticated";

grant update on table "public"."join_training_requests" to "authenticated";

grant delete on table "public"."join_training_requests" to "service_role";

grant insert on table "public"."join_training_requests" to "service_role";

grant references on table "public"."join_training_requests" to "service_role";

grant select on table "public"."join_training_requests" to "service_role";

grant trigger on table "public"."join_training_requests" to "service_role";

grant truncate on table "public"."join_training_requests" to "service_role";

grant update on table "public"."join_training_requests" to "service_role";

grant delete on table "public"."notices" to "anon";

grant insert on table "public"."notices" to "anon";

grant references on table "public"."notices" to "anon";

grant select on table "public"."notices" to "anon";

grant trigger on table "public"."notices" to "anon";

grant truncate on table "public"."notices" to "anon";

grant update on table "public"."notices" to "anon";

grant delete on table "public"."notices" to "authenticated";

grant insert on table "public"."notices" to "authenticated";

grant references on table "public"."notices" to "authenticated";

grant select on table "public"."notices" to "authenticated";

grant trigger on table "public"."notices" to "authenticated";

grant truncate on table "public"."notices" to "authenticated";

grant update on table "public"."notices" to "authenticated";

grant delete on table "public"."notices" to "service_role";

grant insert on table "public"."notices" to "service_role";

grant references on table "public"."notices" to "service_role";

grant select on table "public"."notices" to "service_role";

grant trigger on table "public"."notices" to "service_role";

grant truncate on table "public"."notices" to "service_role";

grant update on table "public"."notices" to "service_role";

grant delete on table "public"."promo_codes" to "anon";

grant insert on table "public"."promo_codes" to "anon";

grant references on table "public"."promo_codes" to "anon";

grant select on table "public"."promo_codes" to "anon";

grant trigger on table "public"."promo_codes" to "anon";

grant truncate on table "public"."promo_codes" to "anon";

grant update on table "public"."promo_codes" to "anon";

grant delete on table "public"."promo_codes" to "authenticated";

grant insert on table "public"."promo_codes" to "authenticated";

grant references on table "public"."promo_codes" to "authenticated";

grant select on table "public"."promo_codes" to "authenticated";

grant trigger on table "public"."promo_codes" to "authenticated";

grant truncate on table "public"."promo_codes" to "authenticated";

grant update on table "public"."promo_codes" to "authenticated";

grant delete on table "public"."promo_codes" to "service_role";

grant insert on table "public"."promo_codes" to "service_role";

grant references on table "public"."promo_codes" to "service_role";

grant select on table "public"."promo_codes" to "service_role";

grant trigger on table "public"."promo_codes" to "service_role";

grant truncate on table "public"."promo_codes" to "service_role";

grant update on table "public"."promo_codes" to "service_role";

grant delete on table "public"."trainers_groups" to "anon";

grant insert on table "public"."trainers_groups" to "anon";

grant references on table "public"."trainers_groups" to "anon";

grant select on table "public"."trainers_groups" to "anon";

grant trigger on table "public"."trainers_groups" to "anon";

grant truncate on table "public"."trainers_groups" to "anon";

grant update on table "public"."trainers_groups" to "anon";

grant delete on table "public"."trainers_groups" to "authenticated";

grant insert on table "public"."trainers_groups" to "authenticated";

grant references on table "public"."trainers_groups" to "authenticated";

grant select on table "public"."trainers_groups" to "authenticated";

grant trigger on table "public"."trainers_groups" to "authenticated";

grant truncate on table "public"."trainers_groups" to "authenticated";

grant update on table "public"."trainers_groups" to "authenticated";

grant delete on table "public"."trainers_groups" to "service_role";

grant insert on table "public"."trainers_groups" to "service_role";

grant references on table "public"."trainers_groups" to "service_role";

grant select on table "public"."trainers_groups" to "service_role";

grant trigger on table "public"."trainers_groups" to "service_role";

grant truncate on table "public"."trainers_groups" to "service_role";

grant update on table "public"."trainers_groups" to "service_role";

grant delete on table "public"."trainers_trainings" to "anon";

grant insert on table "public"."trainers_trainings" to "anon";

grant references on table "public"."trainers_trainings" to "anon";

grant select on table "public"."trainers_trainings" to "anon";

grant trigger on table "public"."trainers_trainings" to "anon";

grant truncate on table "public"."trainers_trainings" to "anon";

grant update on table "public"."trainers_trainings" to "anon";

grant delete on table "public"."trainers_trainings" to "authenticated";

grant insert on table "public"."trainers_trainings" to "authenticated";

grant references on table "public"."trainers_trainings" to "authenticated";

grant select on table "public"."trainers_trainings" to "authenticated";

grant trigger on table "public"."trainers_trainings" to "authenticated";

grant truncate on table "public"."trainers_trainings" to "authenticated";

grant update on table "public"."trainers_trainings" to "authenticated";

grant delete on table "public"."trainers_trainings" to "service_role";

grant insert on table "public"."trainers_trainings" to "service_role";

grant references on table "public"."trainers_trainings" to "service_role";

grant select on table "public"."trainers_trainings" to "service_role";

grant trigger on table "public"."trainers_trainings" to "service_role";

grant truncate on table "public"."trainers_trainings" to "service_role";

grant update on table "public"."trainers_trainings" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."users_groups" to "anon";

grant insert on table "public"."users_groups" to "anon";

grant references on table "public"."users_groups" to "anon";

grant select on table "public"."users_groups" to "anon";

grant trigger on table "public"."users_groups" to "anon";

grant truncate on table "public"."users_groups" to "anon";

grant update on table "public"."users_groups" to "anon";

grant delete on table "public"."users_groups" to "authenticated";

grant insert on table "public"."users_groups" to "authenticated";

grant references on table "public"."users_groups" to "authenticated";

grant select on table "public"."users_groups" to "authenticated";

grant trigger on table "public"."users_groups" to "authenticated";

grant truncate on table "public"."users_groups" to "authenticated";

grant update on table "public"."users_groups" to "authenticated";

grant delete on table "public"."users_groups" to "service_role";

grant insert on table "public"."users_groups" to "service_role";

grant references on table "public"."users_groups" to "service_role";

grant select on table "public"."users_groups" to "service_role";

grant trigger on table "public"."users_groups" to "service_role";

grant truncate on table "public"."users_groups" to "service_role";

grant update on table "public"."users_groups" to "service_role";

grant delete on table "public"."users_trainings" to "anon";

grant insert on table "public"."users_trainings" to "anon";

grant references on table "public"."users_trainings" to "anon";

grant select on table "public"."users_trainings" to "anon";

grant trigger on table "public"."users_trainings" to "anon";

grant truncate on table "public"."users_trainings" to "anon";

grant update on table "public"."users_trainings" to "anon";

grant delete on table "public"."users_trainings" to "authenticated";

grant insert on table "public"."users_trainings" to "authenticated";

grant references on table "public"."users_trainings" to "authenticated";

grant select on table "public"."users_trainings" to "authenticated";

grant trigger on table "public"."users_trainings" to "authenticated";

grant truncate on table "public"."users_trainings" to "authenticated";

grant update on table "public"."users_trainings" to "authenticated";

grant delete on table "public"."users_trainings" to "service_role";

grant insert on table "public"."users_trainings" to "service_role";

grant references on table "public"."users_trainings" to "service_role";

grant select on table "public"."users_trainings" to "service_role";

grant trigger on table "public"."users_trainings" to "service_role";

grant truncate on table "public"."users_trainings" to "service_role";

grant update on table "public"."users_trainings" to "service_role";

create policy "Authenticated and Anon"
on "public"."addresses"
as permissive
for all
to authenticated, anon, dashboard_user
using (true)
with check (true);


create policy " Authenticated and Anon"
on "public"."categories"
as permissive
for all
to anon, authenticated, dashboard_user
using (true)
with check (true);


create policy " Authenticated and Anon"
on "public"."club_groups"
as permissive
for all
to anon, authenticated, dashboard_user
using (true)
with check (true);



