create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "message" text,
    "is_read" boolean default false
);


alter table "public"."notifications" enable row level security;

alter table "public"."group_trainings" add column "level" integer;

alter table "public"."history_events" add column "from_id" bigint;

alter table "public"."history_events" add column "to_id" bigint;

alter table "public"."notices" add column "user_id" bigint;

alter table "public"."users_trainings" add column "is_active" boolean not null default true;

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."history_events" add constraint "history_events_from_id_fkey" FOREIGN KEY (from_id) REFERENCES users(id) not valid;

alter table "public"."history_events" validate constraint "history_events_from_id_fkey";

alter table "public"."history_events" add constraint "history_events_to_id_fkey" FOREIGN KEY (to_id) REFERENCES users(id) not valid;

alter table "public"."history_events" validate constraint "history_events_to_id_fkey";

alter table "public"."notices" add constraint "notices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."notices" validate constraint "notices_user_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.accept_join_training_request(request_id integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$declare
_user_id int;
_training_id int;
_new_record_id int;
_existing_record_id int;
begin 

select user_id, training_id 
into _user_id, _training_id
from join_training_requests 
where id = request_id and (is_accepted = false and is_rejected = false);

if _user_id is null then
return -1;
end if;

select id into _existing_record_id
from users_trainings
where user_id = _user_id and training_id = _training_id;

if _existing_record_id is null then

update join_training_requests
set is_accepted = true
where id = request_id;

insert into users_trainings (user_id, training_id, is_active)
values (_user_id, _training_id, true)
returning id into _new_record_id;

return _new_record_id;

end if;

return _existing_record_id;
end;$function$
;

CREATE OR REPLACE FUNCTION public.create_group_trainings(_group_id integer, _club_id integer, _from_date timestamp without time zone, _till_date timestamp without time zone, _start_time time without time zone, _end_time time without time zone, _max_occupancy integer, _level integer, _once_in_number_of_weeks integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  _current_date timestamp;
  _start_timestamp timestamp;
  _end_timestamp timestamp;
begin
  -- Initialize the current date to the start date
  _current_date := _from_date;

  -- Loop through the date range and insert rows
  while _current_date <= _till_date loop
    -- Calculate the start and end timestamps for the training
    _start_timestamp := date_trunc('day', _current_date) + _start_time::interval;
    _end_timestamp := date_trunc('day', _current_date) + _end_time::interval;

    -- Insert the training row
    insert into group_trainings (group_id, club_id, start_timestamp, end_timestamp, max_occupancy, level)
    values (_group_id, _club_id, _start_timestamp, _end_timestamp, _max_occupancy, _level);

    -- Increment the current date by the interval (in weeks)
    _current_date := _current_date + (_once_in_number_of_weeks * 7) * interval '1 day';
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_trainings(_group_id integer, _from_date timestamp without time zone, _till_date timestamp without time zone)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  _club_id int;
  _start_time time;
  _end_time time;
  _max_occupancy int;
  _level int;
  _once_in_number_of_weeks int;
  _current_date timestamp;
  _start_timestamp timestamp;
  _end_timestamp timestamp;
  _group_day int;
  _from_day int;
begin
  -- Fetch group details
  select club_id, start_time, end_time, max_occupancy, level, once_in_number_of_weeks, extract(dow from start_time::timestamp)
  into _club_id, _start_time, _end_time, _max_occupancy, _level, _once_in_number_of_weeks, _group_day
  from club_groups
  where id = _group_id;

  -- Get the day of the week for the _from_date (0 = Sunday, 1 = Monday, ..., 6 = Saturday)
  _from_day := extract(dow from _from_date);

  -- Adjust _current_date to the first occurrence of the groups day of the week
  if _from_day <= _group_day then
    _current_date := _from_date + (_group_day - _from_day) * interval '1 day';
  else
    _current_date := _from_date + (7 - (_from_day - _group_day)) * interval '1 day';
  end if;

  -- Loop through the date range and insert rows
  while _current_date <= _till_date loop
    -- Calculate the start and end timestamps for the training
    _start_timestamp := _current_date + make_interval(hours => extract(hour from _start_time), minutes => extract(minute from _start_time));
    _end_timestamp := _current_date + make_interval(hours => extract(hour from _end_time), minutes => extract(minute from _end_time));

    -- Insert the training row
    insert into group_trainings (group_id, club_id, start_timestamp, end_timestamp, max_occupancy, level)
    values (_group_id, _club_id, _start_timestamp, _end_timestamp, _max_occupancy, _level);

    -- Increment the current date by the interval (in weeks)
    _current_date := _current_date + (_once_in_number_of_weeks * 7) * interval '1 day';
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_trainings_batch(_trainings jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  training jsonb;
  inserted_training_id bigint;
begin
  if _trainings is null
    or jsonb_typeof(_trainings) <> 'array'
    or jsonb_array_length(_trainings) = 0 then
    return;
  end if;

  for training in select jsonb_array_elements(_trainings) loop
    insert into group_trainings (
      group_id,
      club_id,
      start_timestamp,
      end_timestamp,
      max_occupancy,
      level
    )
    values (
      (training->>'group_id')::int,
      (training->>'club_id')::int,
      (training->>'start_timestamp')::timestamp,
      (training->>'end_timestamp')::timestamp,
      (training->>'max_occupancy')::int,
      (training->>'level')::int
    )
    returning id into inserted_training_id;

    insert into users_trainings (user_id, training_id)
    select ug.user_id, inserted_training_id
    from users_groups ug
    where ug.club_group_id = (training->>'group_id')::int
      and ug.is_active = true
      and not exists (
        select 1
        from users_trainings ut
        where ut.user_id = ug.user_id
          and ut.training_id = inserted_training_id
      );

    insert into trainers_trainings (trainer_id, training_id)
    select tg.trainer_id, inserted_training_id
    from trainers_groups tg
    where tg.club_group_id = (training->>'group_id')::int
      and not exists (
        select 1
        from trainers_trainings tt
        where tt.trainer_id = tg.trainer_id
          and tt.training_id = inserted_training_id
      );
  end loop;
exception when others then
  raise exception 'Error inserting trainings: %', sqlerrm;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_trainings_with_users(_group_id integer, _from_date timestamp without time zone, _till_date timestamp without time zone)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  _club_id int;
  _start_time time;
  _end_time time;
  _max_occupancy int;
  _level int;
  _once_in_number_of_weeks int;
  _current_date timestamp;
  _start_timestamp timestamp;
  _end_timestamp timestamp;
  _new_training_id int;
begin
  -- Fetch group details
  select club_id, start_time, end_time, max_occupancy, level, once_in_number_of_weeks
  into _club_id, _start_time, _end_time, _max_occupancy, _level, _once_in_number_of_weeks
  from club_groups
  where id = _group_id;

  -- Delete all future training rows for the group
  delete from group_trainings
  where group_id = _group_id
    and start_timestamp >= _from_date;

  -- Initialize the current date to the start date
  _current_date := _from_date;

  -- Loop through the date range and insert rows
  while _current_date <= _till_date loop
    -- Calculate the start and end timestamps for the training
    _start_timestamp := _current_date + (_start_time)::interval;
    _end_timestamp := _current_date + (_end_time)::interval;

    -- Insert the training row and get its ID
    insert into group_trainings (group_id, club_id, start_timestamp, end_timestamp, max_occupancy, level)
    values (_group_id, _club_id, _start_timestamp, _end_timestamp, _max_occupancy, _level)
    returning id into _new_training_id;

    -- Assign users from `users_groups` to the new training row in `users_trainings`
    insert into users_trainings (user_id, training_id, is_active)
    select user_id, _new_training_id, true
    from users_groups
    where club_group_id = _group_id;

    -- Increment the current date by the interval (in weeks)
    _current_date := _current_date + (_once_in_number_of_weeks * 7) * interval '1 day';
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_join_group_request(request_id integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$declare
_user_id int;
_club_group_id int;
_new_record_id int;
_existing_record_id int;
begin 

select user_id, club_group_id 
into _user_id, _club_group_id
from join_group_requests 
where id = request_id and (is_accepted = false and is_rejected = false);

if _user_id is null then
return -1;
end if;

select id into _existing_record_id
from users_groups
where user_id = _user_id and club_group_id = _club_group_id;

if _existing_record_id is null then

update join_group_requests
set is_accepted = true
where id = request_id;

insert into users_groups (user_id, club_group_id, is_active)
values (_user_id, _club_group_id, true)
returning id into _new_record_id;

return _new_record_id;

end if;

return _existing_record_id;
end;$function$
;

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";


